[build]
  command = "pnpm run build"
  # Folder 'dist' adalah tempat Nuxt menyimpan aset statis saat build untuk Netlify
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.22.2" # Gunakan versi stabil yang tadi terdeteksi di log (v22)
  PNPM_VERSION = "10.30.3"