[[build]
  command = "pnpm run build && ls -la .output"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "24"
  PNPM_FLAGS = "--shamefully-hoist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"